on:
  push:
    branches:
      - main
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: generate-matrix
        run: |
          matrix='{"include":[{"version": 10},{"version": 12},{"version": 14}]}'
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
  example:
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - id: x
        uses: jdolitsky/actions/matrix-extra-inputs@matrix-extra-inputs
        with:
          matrix-json: ${{ toJSON(matrix) }}
        env:
          EXTRA_INPUT_CHECK_IT_OUT: hello
      - run: |
          set -x
          echo '${{ steps.x.outputs.abc }}'
      #- uses: jdolitsky/actions/matrix-check-inputs@matrix-extra-inputs
      #  with: ${{ fromJSON(steps.extra-inputs.outputs.matrix-json) }}

      #- uses: jdolitsky/actions/matrix-check-inputs@matrix-extra-inputs
      #  with: ${{ fromJSON(steps.extra-inputs.outputs.matrix-json) }}
