on:
  push:
    branches:
      - main
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - uses: jdolitsky/actions/matrix-extra-inputs@matrix-extra-inputs
        with:
          matrix-json: ${{ toJSON(matrix) }}
        env:
          EXTRA_INPUT_CHECK_IT_OUT: hello
