on:
  push:
    branches:
      - main
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - run: |
          echo '${{ toJSON(matrix) }}' | jq
